version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - flachag
    assignees:
      - flachag
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
